### 게시물 보기
GET http://localhost:8080/board/1/post/1
Content-Type: application/json

### 게시물 작성
POST http://localhost:8080/board/1/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxQDEiLCJhdXRoIjoiTiIsImV4cCI6MTcxODYxODg2OH0.k4hJizGiIBN48jCr8w5d_lxOPVBTxckvJB4llovzXJqrwq2WVKmBrZ2MykoX6sfjC1waxHaXx_fYZn8bLg4LVg

{
  "title" : "13213123213",
  "content": "13213213"
}

### 게시물 수정
PUT http://localhost:8080/board/1/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxQDIiLCJhdXRoIjoiTiIsImV4cCI6MTcxNzkzODU5MH0.OOCcC0O-p5MvSstlBBI8bBlrI8sZ_8BOeV4QTufM2SRMUeF0OsOCChbAXTcFcwTzVUZDGxc4bBqrs5RiqrfGRw

{
  "postId" : 1,
  "title" : "12312321",
  "content": "1235454VDF"
}

### 게시물 삭제
DELETE http://localhost:8080/board/1/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxQDIiLCJhdXRoIjoiTiIsImV4cCI6MTcxNzkzODU5MH0.OOCcC0O-p5MvSstlBBI8bBlrI8sZ_8BOeV4QTufM2SRMUeF0OsOCChbAXTcFcwTzVUZDGxc4bBqrs5RiqrfGRw

{
  "postId" : 3
}

### 게시물 임시 저장
POST http://localhost:8080/board/1/post/temporary
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxQDEiLCJhdXRoIjoiTiIsImV4cCI6MTcxODYxNTEyMn0.l-wk05lrrWb36wvu5kePCQXUfW-SWvZt7ZYt6EmKg6zNzuTk2uDkJPujD2qiHoBh8YvH44BA4pDrpv2wNQfIPg

{
  "title" : "1",
  "content": "12312421"
}

### 게시물 임시 저장물 가져오기
GET http://localhost:8080/board/1/post/temporary
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxQDEiLCJhdXRoIjoiTiIsImV4cCI6MTcxODYxNTEyMn0.l-wk05lrrWb36wvu5kePCQXUfW-SWvZt7ZYt6EmKg6zNzuTk2uDkJPujD2qiHoBh8YvH44BA4pDrpv2wNQfIPg

{
  "title" : "1"
}

### 게시물 임시 저장물 삭제하기
DELETE http://localhost:8080/board/1/post/temporary
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxQDEiLCJhdXRoIjoiTiIsImV4cCI6MTcxODYxNTEyMn0.l-wk05lrrWb36wvu5kePCQXUfW-SWvZt7ZYt6EmKg6zNzuTk2uDkJPujD2qiHoBh8YvH44BA4pDrpv2wNQfIPg

{
  "title" : "1"
}

### 게시물 추천 기능 실행
PUT http://localhost:8080/board/1/post/1/likes/up
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxQDEiLCJhdXRoIjoiTiIsImV4cCI6MTcxODYxODY0Mn0.Y7L8kcJb31UohLDZMMcP3OeqxhVFU4La_gXEd0FrZbkB3UEJUDRSLpr_PvCYo31g3Vs-vlYpYauhnmvmgxN2fQ


### 게시물 검색 (검색어 x)
GET http://localhost:8080/board/1/post/list
Content-Type: application/json

### 게시물 검색 (검색어 0 / 타입지정 x)
GET http://localhost:8080/board/1/post/list?searchText=ㅋ
Content-Type: application/json

### 게시물 검색 (검색어 0 / 타입 : 게시자)
GET http://localhost:8080/board/1/post/list?searchText=@3&type=user
Content-Type: application/json

### 게시물 검색 (검색어 0 / 타입 : 제목)
GET http://localhost:8080/board/1/post/list?searchText=2&type=title
Content-Type: application/json

### 게시물 검색 (검색어 0 / 타입 : 내용물)
GET http://localhost:8080/board/1/post/list?searchText=2&type=content
Content-Type: application/json

### 게시물 검색 (페이지 네이션 설정 변경)
GET http://localhost:8080/board/1/post/list?page=10&size=5
Content-Type: application/json